services:
  lawyer.api.commercialplans.webapi:
    image: lawyer.api.commercialplans.webapi
    build:
      context: .
      dockerfile: lawyer.api.commercialplans.webapi/Dockerfile
    ports:
      - "8082:8080"
